"""added password filed

Revision ID: ce468f863c94
Revises: ca61cd67792e
Create Date: 2025-02-10 21:13:59.930819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce468f863c94'
down_revision: Union[str, None] = 'ca61cd67792e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_Users_password'), 'Users', ['password'], unique=True)
    op.create_unique_constraint(None, 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_index(op.f('ix_Users_password'), table_name='Users')
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###
