"""practice data

Revision ID: fc2f2772216d
Revises: ce468f863c94
Create Date: 2025-02-17 13:27:33.473629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2f2772216d'
down_revision: Union[str, None] = 'ce468f863c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practiceDB',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('work', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practiceDB_id'), 'practiceDB', ['id'], unique=False)
    op.drop_index('ix_Users_email', table_name='Users')
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.drop_index('ix_Users_password', table_name='Users')
    op.create_index(op.f('ix_Users_password'), 'Users', ['password'], unique=False)
    op.drop_index('ix_Users_username', table_name='Users')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index('ix_Users_username', 'Users', ['username'], unique=True)
    op.drop_index(op.f('ix_Users_password'), table_name='Users')
    op.create_index('ix_Users_password', 'Users', ['password'], unique=True)
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    op.drop_index(op.f('ix_practiceDB_id'), table_name='practiceDB')
    op.drop_table('practiceDB')
    # ### end Alembic commands ###
